version: 2
jobs:
  build:
    docker:
      - image: rust
    environment:
      - RUSTDOCFLAGS: "-Cpanic=abort"
    steps:
      - checkout
      - run: RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
      - run: rustup toolchain install nightly
      - run: rustup component add clippy
      - run: cargo build
      - run: cargo test
      - run: cargo clippy
      - run: cargo tarpaulin --out Xml
      - run: cargo +nightly build
      - run: cargo +nightly test
      - run:
          name: Uploading code coverage
          command: |
              bash <(curl -s https://codecov.io/bash)
